Fix parser exception when memory value is missing
```
[NoMethodError]: undefined method `/' for nil:NilClass
manageiq-providers-kubevirt/app/models/manageiq/providers/kubevirt/inventory/parser.rb:151:in `process_domain'
```